logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor: TRACE

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema_tickets_27_july_2024?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: ${db_password}
    username: ${db_username}

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  cinema_tickets:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:123456}
    remember.me.key: ${REMEMBER_ME_KEY:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
mail:
  cinema_tickets: c_tickets@gmail.com
  host: localhost
  port: 1025
  username: ${MAIL_USER:softuni}
  password: ${MAIL_PASSWORD:softuni}

  version: "3"
  services:
    mail-hog:
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - 1025:1025
        - 8025:8025